force-app/main/default/objects/Campaign_Member__c/Campaign_Member__c.object-meta.xml
<CustomObject>
    <label>Campaign Member</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>Member</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_Member__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>Campaign_Members</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Campaign_Member__c/fields/Marketing_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Campaign__c</fullName>
    <label>Marketing Campaign</label>
    <referenceTo>Marketing_Campaign__c</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>Campaign_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_request__c/Job_request__c.object-meta.xml
<CustomObject>
    <label>Job request</label>
    <nameField>
        <displayFormat>JR-{000000}</displayFormat>
        <label>Job request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_request__c/fields/Job_Status__c.field-meta.xml
<CustomField>
    <fullName>Job_Status__c</fullName>
    <label>Job Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
            <value>
                <fullName>Finished with an error</fullName>
            </value>
            <value>
                <fullName>Failed to run</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/Marketing_Campaign__c.object-meta.xml
<CustomObject>
    <label>Marketing Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SendCampaignEmails.cls
public class SendCampaignEmails implements Database.Batchable<sObject> {
    CampaignEmailsJob params;
    
    public SendCampaignEmails(CampaignEmailsJob params){
        this.params = params;
    }
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Contact__r.Email FROM Campaign_Member__c WHERE Marketing_Campaign__c = \'' + this.params.campaignId +  '\'';
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext bc, List<Campaign_Member__c> campaignMembers){
        String emailTempalteId = this.params.emailTemplateId;
        for(Campaign_Member__c campaignMember : campaignMembers){
            // send emails for campaign members using template and contact's email
        }
    }
    
    public void finish(Database.BatchableContext bc){
        AsyncApexJob batchJob = [
            SELECT Status
            FROM AsyncApexJob WHERE Id = :bc.getJobId()
        ];
        
        update new Job_request__c(
            Id = this.params.jobRequestId,
            Job_Status__c = batchJob.Status == 'Failed' ? 'Finished with an error' : 'Finished'
        );
    }
    
    public class CampaignEmailsJob{
        public String jobRequestId;
        public String campaignId;
        public String emailTemplateId;
    }
}