force-app/main/default/objects/Job_request__c/Job_request__c.object-meta.xml
<CustomObject>
    <label>Job request</label>
    <nameField>
        <displayFormat>JR-{000000}</displayFormat>
        <label>Job request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_request__c/fields/Job_Parameters__c.field-meta.xml
<CustomField>
    <fullName>Job_Parameters__c</fullName>
    <description>JSON parameters</description>
    <label>Job Parameters</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job_request__c/fields/Job_Status__c.field-meta.xml
<CustomField>
    <fullName>Job_Status__c</fullName>
    <label>Job Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
            <value>
                <fullName>Finished with an error</fullName>
            </value>
            <value>
                <fullName>Failed to run</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_request__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Marketing Email Sending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SendEmailForCampaignButtonCtrl.cls
public class SendEmailForCampaignButtonCtrl {
    @AuraEnabled
    public static void sendEmailsForCampaign(String campaignId){
        SendCampaignEmails.CampaignEmailsJob params = new SendCampaignEmails.CampaignEmailsJob();
        params.campaignId = campaignId;
        params.emailTemplateId = '00X7Q000002eyEHUAY';
        
        insert new Job_request__c(
            Job_Type__c = JobOrchestrator.MARKETING_EMAIL_JOB, 
            Job_Parameters__c = JSON.serialize(params),
            Job_Status__c = 'New'
        );
    }
}